import { Scenario } from '@/lib/types';

export const gossipAntiEntropyScenarios: Scenario[] = [
  {
    id: 'rumor-spread-push',
    name: 'Rumor Spread (Push)',
    concept: 'gossip-anti-entropy',
    description: 'A new value spreads via push-based gossip rounds.',
    initialState: {
      nodeCount: 6,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'set_value',
        description: 'N0 sets feature:flag=true',
        data: { nodeId: 'N0', key: 'feature:flag', value: true },
      },
      {
        id: 1,
        timestamp: 600,
        type: 'gossip_round',
        description: 'Push gossip round (fanout=1)',
        data: { mode: 'push', fanout: 1 },
      },
      {
        id: 2,
        timestamp: 1400,
        type: 'gossip_round',
        description: 'Push gossip round (fanout=1)',
        data: { mode: 'push', fanout: 1 },
      },
      {
        id: 3,
        timestamp: 2200,
        type: 'gossip_round',
        description: 'Push gossip round (fanout=1)',
        data: { mode: 'push', fanout: 1 },
      },
    ],
    learningObjectives: [
      'Observe push-based gossip propagation',
      'See how fanout impacts spread speed',
      'Understand anti-entropy convergence',
    ],
    expectedOutcome: 'Most nodes learn the new value after a few rounds.',
  },
  {
    id: 'pull-catchup',
    name: 'Pull-Based Catch-Up',
    concept: 'gossip-anti-entropy',
    description: 'A stale node catches up by pulling state.',
    initialState: {
      nodeCount: 5,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'set_value',
        description: 'N1 sets prices:sku123=25',
        data: { nodeId: 'N1', key: 'prices:sku123', value: 25 },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'set_value',
        description: 'N3 sets prices:sku123=27',
        data: { nodeId: 'N3', key: 'prices:sku123', value: 27 },
      },
      {
        id: 2,
        timestamp: 1200,
        type: 'gossip_round',
        description: 'Pull gossip round (fanout=1)',
        data: { mode: 'pull', fanout: 1 },
      },
      {
        id: 3,
        timestamp: 2000,
        type: 'gossip_round',
        description: 'Pull gossip round (fanout=1)',
        data: { mode: 'pull', fanout: 1 },
      },
    ],
    learningObjectives: [
      'Understand pull-based anti-entropy',
      'See how stale nodes request newer state',
      'Compare with push behavior',
    ],
    expectedOutcome: 'Nodes converge on the newest version for the key.',
  },
  {
    id: 'failure-and-recovery',
    name: 'Failure and Recovery',
    concept: 'gossip-anti-entropy',
    description: 'A failed node recovers and syncs via gossip.',
    initialState: {
      nodeCount: 6,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'set_value',
        description: 'N2 sets session:abc={userId: 42}',
        data: { nodeId: 'N2', key: 'session:abc', value: { userId: 42 } },
      },
      {
        id: 1,
        timestamp: 600,
        type: 'fail_node',
        description: 'N4 fails',
        data: { nodeId: 'N4' },
      },
      {
        id: 2,
        timestamp: 1200,
        type: 'set_value',
        description: 'N1 sets session:def={userId: 99}',
        data: { nodeId: 'N1', key: 'session:def', value: { userId: 99 } },
      },
      {
        id: 3,
        timestamp: 1800,
        type: 'recover_node',
        description: 'N4 recovers',
        data: { nodeId: 'N4' },
      },
      {
        id: 4,
        timestamp: 2400,
        type: 'gossip_round',
        description: 'Push-pull gossip round (fanout=1)',
        data: { mode: 'push-pull', fanout: 1 },
      },
      {
        id: 5,
        timestamp: 3200,
        type: 'gossip_round',
        description: 'Push-pull gossip round (fanout=1)',
        data: { mode: 'push-pull', fanout: 1 },
      },
    ],
    learningObjectives: [
      'See recovery catch-up without a central coordinator',
      'Understand resilience of gossip protocols',
      'Observe convergence after failures',
    ],
    expectedOutcome: 'Recovered node learns the missed updates via gossip.',
  },
  {
    id: 'multi-key-convergence',
    name: 'Multi-Key Convergence',
    concept: 'gossip-anti-entropy',
    description: 'Multiple keys converge using push-pull rounds.',
    initialState: {
      nodeCount: 7,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'set_value',
        description: 'N0 sets inventory:apple=100',
        data: { nodeId: 'N0', key: 'inventory:apple', value: 100 },
      },
      {
        id: 1,
        timestamp: 300,
        type: 'set_value',
        description: 'N2 sets inventory:banana=80',
        data: { nodeId: 'N2', key: 'inventory:banana', value: 80 },
      },
      {
        id: 2,
        timestamp: 600,
        type: 'set_value',
        description: 'N5 sets inventory:cherry=60',
        data: { nodeId: 'N5', key: 'inventory:cherry', value: 60 },
      },
      {
        id: 3,
        timestamp: 1200,
        type: 'gossip_round',
        description: 'Push-pull gossip round (fanout=2)',
        data: { mode: 'push-pull', fanout: 2 },
      },
      {
        id: 4,
        timestamp: 2000,
        type: 'gossip_round',
        description: 'Push-pull gossip round (fanout=2)',
        data: { mode: 'push-pull', fanout: 2 },
      },
      {
        id: 5,
        timestamp: 2800,
        type: 'gossip_round',
        description: 'Push-pull gossip round (fanout=2)',
        data: { mode: 'push-pull', fanout: 2 },
      },
    ],
    learningObjectives: [
      'See fanout effects on convergence speed',
      'Understand anti-entropy with multiple keys',
      'Observe push-pull efficiency',
    ],
    expectedOutcome: 'All nodes converge on all keys after a few rounds.',
  },
];
