import { Scenario } from '@/lib/types';

export const vectorClockScenarios: Scenario[] = [
  {
    id: 'basic-causality',
    name: 'Basic Causality',
    concept: 'vector-clocks',
    description: 'Simple message exchange showing causal ordering',
    initialState: {
      processCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'local_event',
        description: 'P0: Local event',
        data: { processId: 'P0', description: 'Initialize' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_message',
        description: 'P0 sends to P1',
        data: { from: 'P0', to: 'P1', message: 'Hello' },
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'receive_message',
        description: 'P1 receives from P0',
        data: { to: 'P1', sendEventId: 'event-1', message: 'Hello' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'local_event',
        description: 'P1: Process message',
        data: { processId: 'P1', description: 'Process' },
      },
      {
        id: 4,
        timestamp: 2000,
        type: 'send_message',
        description: 'P1 sends to P2',
        data: { from: 'P1', to: 'P2', message: 'Forward' },
      },
      {
        id: 5,
        timestamp: 2500,
        type: 'receive_message',
        description: 'P2 receives from P1',
        data: { to: 'P2', sendEventId: 'event-4', message: 'Forward' },
      },
    ],
    learningObjectives: [
      'Understand causal ordering (A → B)',
      'See how vector clocks capture happened-before relationships',
      'Observe clock updates during message passing',
    ],
    expectedOutcome: 'Chain of causally related events: P0 → P1 → P2',
  },
  {
    id: 'concurrent-events',
    name: 'Detecting Concurrent Events',
    concept: 'vector-clocks',
    description: 'Independent events in different processes are concurrent',
    initialState: {
      processCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'local_event',
        description: 'P0: Event A',
        data: { processId: 'P0', description: 'Event A' },
      },
      {
        id: 1,
        timestamp: 100,
        type: 'local_event',
        description: 'P1: Event B (concurrent with A)',
        data: { processId: 'P1', description: 'Event B' },
      },
      {
        id: 2,
        timestamp: 200,
        type: 'local_event',
        description: 'P2: Event C (concurrent with A and B)',
        data: { processId: 'P2', description: 'Event C' },
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'send_message',
        description: 'P0 → P1',
        data: { from: 'P0', to: 'P1', message: 'Sync' },
      },
      {
        id: 4,
        timestamp: 1500,
        type: 'receive_message',
        description: 'P1 receives',
        data: { to: 'P1', sendEventId: 'event-3', message: 'Sync' },
      },
    ],
    learningObjectives: [
      'Understand concurrent events (neither happened before the other)',
      'See how vector clocks detect concurrency',
      'Learn that concurrent events can happen in any order',
    ],
    expectedOutcome: 'Events A, B, C are mutually concurrent',
  },
  {
    id: 'message-chain',
    name: 'Message Chain',
    concept: 'vector-clocks',
    description: 'Messages propagate causality across multiple processes',
    initialState: {
      processCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'local_event',
        description: 'P0: Start',
        data: { processId: 'P0', description: 'Start' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_message',
        description: 'P0 → P1',
        data: { from: 'P0', to: 'P1', message: 'Msg1' },
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'receive_message',
        description: 'P1 receives',
        data: { to: 'P1', sendEventId: 'event-1', message: 'Msg1' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'send_message',
        description: 'P1 → P2',
        data: { from: 'P1', to: 'P2', message: 'Msg2' },
      },
      {
        id: 4,
        timestamp: 2000,
        type: 'receive_message',
        description: 'P2 receives',
        data: { to: 'P2', sendEventId: 'event-3', message: 'Msg2' },
      },
      {
        id: 5,
        timestamp: 2500,
        type: 'send_message',
        description: 'P2 → P0',
        data: { from: 'P2', to: 'P0', message: 'Msg3' },
      },
      {
        id: 6,
        timestamp: 3000,
        type: 'receive_message',
        description: 'P0 receives (causal loop)',
        data: { to: 'P0', sendEventId: 'event-5', message: 'Msg3' },
      },
    ],
    learningObjectives: [
      'See how causality propagates through message chains',
      'Understand vector clock updates across multiple hops',
      'Observe how P0 learns about events in P1 and P2',
    ],
    expectedOutcome: 'Causality flows in a circle: P0 → P1 → P2 → P0',
  },
  {
    id: 'causal-vs-concurrent',
    name: 'Causal vs Concurrent Mix',
    concept: 'vector-clocks',
    description: 'Mix of causally related and concurrent events',
    initialState: {
      processCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'local_event',
        description: 'P0: Event A',
        data: { processId: 'P0', description: 'Event A' },
      },
      {
        id: 1,
        timestamp: 200,
        type: 'local_event',
        description: 'P1: Event B (concurrent with A)',
        data: { processId: 'P1', description: 'Event B' },
      },
      {
        id: 2,
        timestamp: 500,
        type: 'send_message',
        description: 'P0 → P2',
        data: { from: 'P0', to: 'P2', message: 'M1' },
      },
      {
        id: 3,
        timestamp: 700,
        type: 'send_message',
        description: 'P1 → P2',
        data: { from: 'P1', to: 'P2', message: 'M2' },
      },
      {
        id: 4,
        timestamp: 1000,
        type: 'receive_message',
        description: 'P2 receives M1',
        data: { to: 'P2', sendEventId: 'event-2', message: 'M1' },
      },
      {
        id: 5,
        timestamp: 1500,
        type: 'receive_message',
        description: 'P2 receives M2',
        data: { to: 'P2', sendEventId: 'event-3', message: 'M2' },
      },
      {
        id: 6,
        timestamp: 2000,
        type: 'local_event',
        description: 'P2: Merge (causally after both A and B)',
        data: { processId: 'P2', description: 'Merge' },
      },
    ],
    learningObjectives: [
      'Distinguish between causal and concurrent relationships',
      'See how processes merge concurrent histories',
      'Understand partial ordering in distributed systems',
    ],
    expectedOutcome: 'P2 merges information from concurrent events in P0 and P1',
  },
  {
    id: 'broadcast-pattern',
    name: 'Broadcast Pattern',
    concept: 'vector-clocks',
    description: 'One process broadcasts to multiple others',
    initialState: {
      processCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'local_event',
        description: 'P0: Prepare broadcast',
        data: { processId: 'P0', description: 'Prepare' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_message',
        description: 'P0 → P1',
        data: { from: 'P0', to: 'P1', message: 'Broadcast' },
      },
      {
        id: 2,
        timestamp: 600,
        type: 'send_message',
        description: 'P0 → P2',
        data: { from: 'P0', to: 'P2', message: 'Broadcast' },
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'receive_message',
        description: 'P1 receives',
        data: { to: 'P1', sendEventId: 'event-1', message: 'Broadcast' },
      },
      {
        id: 4,
        timestamp: 1200,
        type: 'receive_message',
        description: 'P2 receives',
        data: { to: 'P2', sendEventId: 'event-2', message: 'Broadcast' },
      },
      {
        id: 5,
        timestamp: 1500,
        type: 'local_event',
        description: 'P1: Process',
        data: { processId: 'P1', description: 'Process' },
      },
      {
        id: 6,
        timestamp: 1700,
        type: 'local_event',
        description: 'P2: Process (concurrent with P1)',
        data: { processId: 'P2', description: 'Process' },
      },
    ],
    learningObjectives: [
      'Understand broadcast in distributed systems',
      'See how recipients process messages concurrently',
      'Learn about common communication patterns',
    ],
    expectedOutcome: 'P1 and P2 receive same causal history but process concurrently',
  },
];
