import { Scenario } from '@/lib/types';

export const raftScenarios: Scenario[] = [
  {
    id: 'basic-election',
    name: 'Basic Leader Election',
    concept: 'raft',
    description: 'Watch a basic leader election process in a healthy cluster',
    initialState: {
      nodeCount: 5,
      failedNodes: [],
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_election',
        description: 'Node 0 election timeout, starts election',
        data: { nodeId: 'node-0' },
      },
      {
        id: 1,
        timestamp: 100,
        type: 'request_vote',
        description: 'Process RequestVote messages',
        data: {},
      },
      {
        id: 2,
        timestamp: 200,
        type: 'vote_response',
        description: 'Process vote responses',
        data: {},
      },
      {
        id: 3,
        timestamp: 300,
        type: 'leader_elected',
        description: 'Leader is elected',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand how a candidate requests votes',
      'See majority quorum in action',
      'Observe state transitions from follower to candidate to leader',
    ],
    expectedOutcome: 'One node becomes leader and others remain followers',
  },
  {
    id: 'leader-failure',
    name: 'Leader Failure',
    concept: 'raft',
    description: 'Leader fails and a new leader is elected',
    initialState: {
      nodeCount: 5,
      failedNodes: [],
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_election',
        description: 'Initial election',
        data: { nodeId: 'node-0' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'fail_node',
        description: 'Leader fails',
        data: { nodeId: 'node-0' },
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'start_election',
        description: 'New election starts',
        data: { nodeId: 'node-1' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'leader_elected',
        description: 'New leader elected',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand how Raft handles leader failures',
      'See election timeout in action',
      'Observe automatic failover',
    ],
    expectedOutcome: 'A new leader is elected automatically after the old leader fails',
  },
  {
    id: 'split-brain',
    name: 'Network Partition (Split Brain)',
    concept: 'raft',
    description: 'Cluster is partitioned into two groups',
    initialState: {
      nodeCount: 5,
      failedNodes: [],
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_election',
        description: 'Initial election',
        data: { nodeId: 'node-0' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'network_partition',
        description: 'Network partition: nodes 0,1 | nodes 2,3,4',
        data: { partition: [['node-0', 'node-1'], ['node-2', 'node-3', 'node-4']] },
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'start_election',
        description: 'Election in majority partition',
        data: { nodeId: 'node-2' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'heal_partition',
        description: 'Partition heals',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand network partitions',
      'See how majority partition elects a leader',
      'Observe how minority partition cannot elect a leader',
      'Watch partition healing and reconciliation',
    ],
    expectedOutcome: 'Only the majority partition can elect a leader',
  },
  {
    id: 'log-replication',
    name: 'Log Replication',
    concept: 'raft',
    description: 'Leader replicates log entries to followers',
    initialState: {
      nodeCount: 5,
      failedNodes: [],
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_election',
        description: 'Elect a leader',
        data: { nodeId: 'node-0' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'client_request',
        description: 'Client sends request: SET x=1',
        data: { leaderId: 'node-0', command: 'SET x=1' },
      },
      {
        id: 2,
        timestamp: 700,
        type: 'replicate_log',
        description: 'Leader replicates to followers',
        data: {},
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'client_request',
        description: 'Client sends request: SET y=2',
        data: { leaderId: 'node-0', command: 'SET y=2' },
      },
      {
        id: 4,
        timestamp: 1200,
        type: 'replicate_log',
        description: 'Leader replicates to followers',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand log replication process',
      'See AppendEntries RPCs in action',
      'Observe how logs stay consistent across nodes',
    ],
    expectedOutcome: 'All nodes have the same log entries in the same order',
  },
  {
    id: 'follower-lag',
    name: 'Follower Lagging Behind',
    concept: 'raft',
    description: 'A follower is temporarily down and catches up when it recovers',
    initialState: {
      nodeCount: 5,
      failedNodes: [],
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_election',
        description: 'Elect a leader',
        data: { nodeId: 'node-0' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'fail_node',
        description: 'Node 3 fails',
        data: { nodeId: 'node-3' },
      },
      {
        id: 2,
        timestamp: 700,
        type: 'client_request',
        description: 'Client requests while node 3 is down',
        data: { leaderId: 'node-0', command: 'SET x=1' },
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'client_request',
        description: 'Another client request',
        data: { leaderId: 'node-0', command: 'SET y=2' },
      },
      {
        id: 4,
        timestamp: 1500,
        type: 'recover_node',
        description: 'Node 3 recovers',
        data: { nodeId: 'node-3' },
      },
      {
        id: 5,
        timestamp: 1700,
        type: 'catch_up',
        description: 'Node 3 catches up',
        data: { nodeId: 'node-3' },
      },
    ],
    learningObjectives: [
      'Understand how Raft handles node failures',
      'See how lagging nodes catch up',
      'Observe log consistency maintenance',
    ],
    expectedOutcome: 'The recovered node catches up and has the same log as others',
  },
];
