import { Scenario } from '@/lib/types';

export const paxosScenarios: Scenario[] = [
  {
    id: 'basic-consensus',
    name: 'Basic Consensus',
    concept: 'paxos',
    description: 'Single proposer achieves consensus on a value',
    initialState: {
      proposerCount: 2,
      acceptorCount: 5,
      learnerCount: 2,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_proposal',
        description: 'Proposer 0 proposes value "A"',
        data: { proposerId: 'proposer-0', value: 'A' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'handle_prepare',
        description: 'Acceptors respond with promises',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'handle_promise',
        description: 'Proposer receives majority promises',
        data: { value: 'A' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'handle_accept',
        description: 'Acceptors accept the value',
        data: {},
      },
      {
        id: 4,
        timestamp: 2000,
        type: 'consensus_reached',
        description: 'Consensus achieved on value "A"',
        data: { value: 'A' },
      },
    ],
    learningObjectives: [
      'Understand the two-phase Paxos protocol',
      'See Prepare/Promise phase in action',
      'Observe Accept/Accepted phase',
      'Understand majority quorum requirement',
    ],
    expectedOutcome: 'All acceptors agree on value "A"',
  },
  {
    id: 'dueling-proposers',
    name: 'Dueling Proposers',
    concept: 'paxos',
    description: 'Two proposers compete, demonstrating how Paxos handles conflicts',
    initialState: {
      proposerCount: 2,
      acceptorCount: 5,
      learnerCount: 2,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_proposal',
        description: 'Proposer 0 proposes value "X"',
        data: { proposerId: 'proposer-0', value: 'X' },
      },
      {
        id: 1,
        timestamp: 200,
        type: 'start_proposal',
        description: 'Proposer 1 proposes value "Y"',
        data: { proposerId: 'proposer-1', value: 'Y' },
      },
      {
        id: 2,
        timestamp: 500,
        type: 'handle_prepare',
        description: 'Acceptors respond to both proposers',
        data: {},
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'handle_promise',
        description: 'Proposers receive promises',
        data: {},
      },
      {
        id: 4,
        timestamp: 1500,
        type: 'handle_accept',
        description: 'Conflict resolution in progress',
        data: {},
      },
      {
        id: 5,
        timestamp: 2000,
        type: 'consensus_reached',
        description: 'One value wins',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand competing proposals',
      'See how proposal numbers prevent conflicts',
      'Observe which proposer wins based on timing',
      'Learn about livelock prevention',
    ],
    expectedOutcome: 'One proposer wins, consensus is reached on a single value',
  },
  {
    id: 'acceptor-failure',
    name: 'Acceptor Failure',
    concept: 'paxos',
    description: 'Acceptor fails during consensus, system still makes progress',
    initialState: {
      proposerCount: 2,
      acceptorCount: 5,
      learnerCount: 2,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_proposal',
        description: 'Proposer 0 proposes value "A"',
        data: { proposerId: 'proposer-0', value: 'A' },
      },
      {
        id: 1,
        timestamp: 300,
        type: 'fail_node',
        description: 'Acceptor 2 fails',
        data: { nodeId: 'acceptor-2' },
      },
      {
        id: 2,
        timestamp: 500,
        type: 'handle_prepare',
        description: 'Remaining acceptors respond',
        data: {},
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'handle_promise',
        description: 'Majority still achieved',
        data: { value: 'A' },
      },
      {
        id: 4,
        timestamp: 1500,
        type: 'handle_accept',
        description: 'Consensus with 4 out of 5 acceptors',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand fault tolerance in Paxos',
      'See majority quorum in action',
      'Learn how Paxos tolerates f failures with 2f+1 acceptors',
    ],
    expectedOutcome: 'Consensus is reached despite one failed acceptor',
  },
  {
    id: 'late-proposer',
    name: 'Late Proposer',
    concept: 'paxos',
    description: 'Proposer starts after value is already accepted',
    initialState: {
      proposerCount: 2,
      acceptorCount: 5,
      learnerCount: 2,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_proposal',
        description: 'Proposer 0 proposes value "First"',
        data: { proposerId: 'proposer-0', value: 'First' },
      },
      {
        id: 1,
        timestamp: 500,
        type: 'handle_prepare',
        description: 'Prepare phase completes',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'handle_promise',
        description: 'Promises received',
        data: { value: 'First' },
      },
      {
        id: 3,
        timestamp: 1500,
        type: 'handle_accept',
        description: 'Value "First" accepted',
        data: {},
      },
      {
        id: 4,
        timestamp: 2000,
        type: 'start_proposal',
        description: 'Late proposer proposes "Second"',
        data: { proposerId: 'proposer-1', value: 'Second' },
      },
      {
        id: 5,
        timestamp: 2500,
        type: 'handle_prepare',
        description: 'Late proposer learns about accepted value',
        data: {},
      },
      {
        id: 6,
        timestamp: 3000,
        type: 'handle_promise',
        description: 'Late proposer must propose "First"',
        data: { value: 'First' },
      },
    ],
    learningObjectives: [
      'Understand value stability in Paxos',
      'See how accepted values are propagated',
      'Learn why proposers must adopt previously accepted values',
    ],
    expectedOutcome: 'Late proposer learns and proposes the already-accepted value',
  },
  {
    id: 'multi-paxos',
    name: 'Multi-Paxos Sequence',
    concept: 'paxos',
    description: 'Multiple consensus instances running in sequence',
    initialState: {
      proposerCount: 2,
      acceptorCount: 5,
      learnerCount: 2,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_proposal',
        description: 'Instance 1: Propose "Command-1"',
        data: { proposerId: 'proposer-0', value: 'Command-1' },
      },
      {
        id: 1,
        timestamp: 1000,
        type: 'consensus_reached',
        description: 'Instance 1: Consensus on "Command-1"',
        data: { value: 'Command-1' },
      },
      {
        id: 2,
        timestamp: 1500,
        type: 'start_proposal',
        description: 'Instance 2: Propose "Command-2"',
        data: { proposerId: 'proposer-0', value: 'Command-2' },
      },
      {
        id: 3,
        timestamp: 2500,
        type: 'consensus_reached',
        description: 'Instance 2: Consensus on "Command-2"',
        data: { value: 'Command-2' },
      },
      {
        id: 4,
        timestamp: 3000,
        type: 'start_proposal',
        description: 'Instance 3: Propose "Command-3"',
        data: { proposerId: 'proposer-1', value: 'Command-3' },
      },
      {
        id: 5,
        timestamp: 4000,
        type: 'consensus_reached',
        description: 'Instance 3: Consensus on "Command-3"',
        data: { value: 'Command-3' },
      },
    ],
    learningObjectives: [
      'Understand Multi-Paxos optimization',
      'See how multiple values can be decided',
      'Learn about instance numbering',
    ],
    expectedOutcome: 'Three consecutive consensus decisions',
  },
];
