import { Scenario } from '@/lib/types';

export const twoPhaseCommitScenarios: Scenario[] = [
  {
    id: 'successful-commit',
    name: 'Successful Commit',
    concept: 'two-phase-commit',
    description: 'All participants vote YES, transaction commits successfully',
    initialState: {
      participantCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Coordinator starts transaction',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Coordinator sends VoteRequest to all participants',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 3,
        timestamp: 1200,
        type: 'participant_vote',
        description: 'participant-1 votes YES',
        data: { participantId: 'participant-1', vote: 'yes' },
      },
      {
        id: 4,
        timestamp: 1400,
        type: 'participant_vote',
        description: 'participant-2 votes YES',
        data: { participantId: 'participant-2', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 2000,
        type: 'coordinator_decide',
        description: 'Coordinator decides to COMMIT',
        data: {},
      },
      {
        id: 6,
        timestamp: 2500,
        type: 'participant_finalize',
        description: 'participant-0 commits',
        data: { participantId: 'participant-0', decision: 'commit' },
      },
      {
        id: 7,
        timestamp: 2700,
        type: 'participant_finalize',
        description: 'participant-1 commits',
        data: { participantId: 'participant-1', decision: 'commit' },
      },
      {
        id: 8,
        timestamp: 2900,
        type: 'participant_finalize',
        description: 'participant-2 commits',
        data: { participantId: 'participant-2', decision: 'commit' },
      },
      {
        id: 9,
        timestamp: 3200,
        type: 'coordinator_complete',
        description: 'Transaction committed successfully',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand the two phases: PREPARE and COMMIT',
      'See unanimous YES votes leading to commit',
      'Observe the coordinator-participant interaction',
    ],
    expectedOutcome: 'Transaction commits successfully across all participants',
  },
  {
    id: 'abort-single-no',
    name: 'Abort on Single NO Vote',
    concept: 'two-phase-commit',
    description: 'One participant votes NO, entire transaction aborts',
    initialState: {
      participantCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Start transaction',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Send VoteRequests',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 3,
        timestamp: 1200,
        type: 'participant_vote',
        description: 'participant-1 votes NO (cannot commit)',
        data: { participantId: 'participant-1', vote: 'no' },
      },
      {
        id: 4,
        timestamp: 1400,
        type: 'participant_vote',
        description: 'participant-2 votes YES',
        data: { participantId: 'participant-2', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 2000,
        type: 'coordinator_decide',
        description: 'Coordinator decides to ABORT (one NO vote)',
        data: {},
      },
      {
        id: 6,
        timestamp: 2500,
        type: 'participant_finalize',
        description: 'participant-0 aborts',
        data: { participantId: 'participant-0', decision: 'abort' },
      },
      {
        id: 7,
        timestamp: 2700,
        type: 'participant_finalize',
        description: 'participant-1 aborts',
        data: { participantId: 'participant-1', decision: 'abort' },
      },
      {
        id: 8,
        timestamp: 2900,
        type: 'participant_finalize',
        description: 'participant-2 aborts',
        data: { participantId: 'participant-2', decision: 'abort' },
      },
      {
        id: 9,
        timestamp: 3200,
        type: 'coordinator_complete',
        description: 'Transaction aborted',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand that a single NO vote aborts the transaction',
      'See the all-or-nothing principle of 2PC',
      'Learn why 2PC ensures atomicity',
    ],
    expectedOutcome: 'Transaction aborts due to single NO vote',
  },
  {
    id: 'participant-failure',
    name: 'Participant Failure During Prepare',
    concept: 'two-phase-commit',
    description: 'Participant fails before voting, transaction must abort',
    initialState: {
      participantCount: 4,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Start transaction',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Send VoteRequests to 4 participants',
        data: {},
      },
      {
        id: 2,
        timestamp: 800,
        type: 'fail_participant',
        description: 'participant-2 fails',
        data: { participantId: 'participant-2' },
      },
      {
        id: 3,
        timestamp: 1000,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 4,
        timestamp: 1200,
        type: 'participant_vote',
        description: 'participant-1 votes YES',
        data: { participantId: 'participant-1', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 1400,
        type: 'participant_vote',
        description: 'participant-3 votes YES',
        data: { participantId: 'participant-3', vote: 'yes' },
      },
      {
        id: 6,
        timestamp: 2000,
        type: 'timeout',
        description: 'Coordinator timeout waiting for participant-2',
        data: {},
      },
      {
        id: 7,
        timestamp: 2500,
        type: 'coordinator_decide',
        description: 'Coordinator decides to ABORT (missing vote)',
        data: {},
      },
      {
        id: 8,
        timestamp: 3000,
        type: 'participant_finalize',
        description: 'participant-0 aborts',
        data: { participantId: 'participant-0', decision: 'abort' },
      },
      {
        id: 9,
        timestamp: 3200,
        type: 'participant_finalize',
        description: 'participant-1 aborts',
        data: { participantId: 'participant-1', decision: 'abort' },
      },
      {
        id: 10,
        timestamp: 3400,
        type: 'participant_finalize',
        description: 'participant-3 aborts',
        data: { participantId: 'participant-3', decision: 'abort' },
      },
      {
        id: 11,
        timestamp: 3700,
        type: 'coordinator_complete',
        description: 'Transaction aborted due to failure',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand how 2PC handles participant failures',
      'See timeout mechanism in action',
      'Learn about the blocking problem of 2PC',
    ],
    expectedOutcome: 'Transaction aborts when participant fails to respond',
  },
  {
    id: 'coordinator-failure-before-commit',
    name: 'Coordinator Failure Before Commit',
    concept: 'two-phase-commit',
    description: 'Coordinator fails after receiving all YES votes but before sending COMMIT',
    initialState: {
      participantCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Start transaction',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Send VoteRequests',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 3,
        timestamp: 1200,
        type: 'participant_vote',
        description: 'participant-1 votes YES',
        data: { participantId: 'participant-1', vote: 'yes' },
      },
      {
        id: 4,
        timestamp: 1400,
        type: 'participant_vote',
        description: 'participant-2 votes YES',
        data: { participantId: 'participant-2', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 1800,
        type: 'fail_coordinator',
        description: 'Coordinator fails before deciding!',
        data: {},
      },
      {
        id: 6,
        timestamp: 2500,
        type: 'show_blocking',
        description: 'Participants BLOCKED (uncertain state)',
        data: {},
      },
    ],
    learningObjectives: [
      'Understand the blocking problem of 2PC',
      'See how coordinator failure leaves participants uncertain',
      'Learn why 3PC was developed to address this',
    ],
    expectedOutcome: 'Participants stuck in PREPARED state, cannot proceed without coordinator',
  },
  {
    id: 'mixed-outcomes',
    name: 'Mixed Votes Leading to Abort',
    concept: 'two-phase-commit',
    description: 'Multiple participants vote differently, requiring abort',
    initialState: {
      participantCount: 5,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Start transaction with 5 participants',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Send VoteRequests to all',
        data: {},
      },
      {
        id: 2,
        timestamp: 1000,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 3,
        timestamp: 1100,
        type: 'participant_vote',
        description: 'participant-1 votes NO',
        data: { participantId: 'participant-1', vote: 'no' },
      },
      {
        id: 4,
        timestamp: 1200,
        type: 'participant_vote',
        description: 'participant-2 votes YES',
        data: { participantId: 'participant-2', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 1300,
        type: 'participant_vote',
        description: 'participant-3 votes NO',
        data: { participantId: 'participant-3', vote: 'no' },
      },
      {
        id: 6,
        timestamp: 1400,
        type: 'participant_vote',
        description: 'participant-4 votes YES',
        data: { participantId: 'participant-4', vote: 'yes' },
      },
      {
        id: 7,
        timestamp: 2000,
        type: 'coordinator_decide',
        description: 'Coordinator decides to ABORT (2 NO votes)',
        data: {},
      },
      {
        id: 8,
        timestamp: 2500,
        type: 'send_aborts',
        description: 'Send ABORT to all participants',
        data: {},
      },
      {
        id: 9,
        timestamp: 3000,
        type: 'all_participants_finalize',
        description: 'All participants abort',
        data: { decision: 'abort' },
      },
      {
        id: 10,
        timestamp: 3500,
        type: 'coordinator_complete',
        description: 'Transaction aborted',
        data: {},
      },
    ],
    learningObjectives: [
      'See how 2PC handles multiple NO votes',
      'Understand the unanimous requirement for commit',
      'Learn about the conservative nature of 2PC',
    ],
    expectedOutcome: 'Transaction aborts when any participant votes NO',
  },
  {
    id: 'recovery-after-failure',
    name: 'Recovery After Participant Failure',
    concept: 'two-phase-commit',
    description: 'Participant fails, recovers, and learns transaction outcome',
    initialState: {
      participantCount: 3,
    },
    events: [
      {
        id: 0,
        timestamp: 0,
        type: 'start_transaction',
        description: 'Start transaction',
        data: {},
      },
      {
        id: 1,
        timestamp: 500,
        type: 'send_vote_requests',
        description: 'Send VoteRequests',
        data: {},
      },
      {
        id: 2,
        timestamp: 700,
        type: 'participant_vote',
        description: 'participant-0 votes YES',
        data: { participantId: 'participant-0', vote: 'yes' },
      },
      {
        id: 3,
        timestamp: 800,
        type: 'fail_participant',
        description: 'participant-1 fails before voting',
        data: { participantId: 'participant-1' },
      },
      {
        id: 4,
        timestamp: 900,
        type: 'participant_vote',
        description: 'participant-2 votes YES',
        data: { participantId: 'participant-2', vote: 'yes' },
      },
      {
        id: 5,
        timestamp: 1500,
        type: 'timeout',
        description: 'Timeout waiting for participant-1',
        data: {},
      },
      {
        id: 6,
        timestamp: 2000,
        type: 'coordinator_decide',
        description: 'Coordinator aborts (missing vote)',
        data: {},
      },
      {
        id: 7,
        timestamp: 2500,
        type: 'participant_finalize',
        description: 'participant-0 aborts',
        data: { participantId: 'participant-0', decision: 'abort' },
      },
      {
        id: 8,
        timestamp: 2700,
        type: 'participant_finalize',
        description: 'participant-2 aborts',
        data: { participantId: 'participant-2', decision: 'abort' },
      },
      {
        id: 9,
        timestamp: 3000,
        type: 'coordinator_complete',
        description: 'Transaction aborted',
        data: {},
      },
      {
        id: 10,
        timestamp: 3500,
        type: 'recover_participant',
        description: 'participant-1 recovers',
        data: { participantId: 'participant-1' },
      },
      {
        id: 11,
        timestamp: 4000,
        type: 'participant_query',
        description: 'participant-1 queries coordinator for outcome',
        data: { participantId: 'participant-1' },
      },
      {
        id: 12,
        timestamp: 4500,
        type: 'participant_finalize',
        description: 'participant-1 learns to abort',
        data: { participantId: 'participant-1', decision: 'abort' },
      },
    ],
    learningObjectives: [
      'Understand recovery protocols in 2PC',
      'See how failed participants catch up',
      'Learn about transaction logs and durability',
    ],
    expectedOutcome: 'Recovered participant learns transaction outcome from coordinator',
  },
];
